<?php
# This file was automatically generated by the MediaWiki 1.35.3
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "/tg/station 13 Wiki";
$wgMetaNamespace = "TG13";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://tgstation13.org";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## UPO means: this is also a user preference option

$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@🌻.invalid";
$wgPasswordSender = "apache@🌻.invalid";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale. This should ideally be set to an English
## language locale so that the behaviour of C library functions will
## be consistent with typical installations. Use $wgLanguageCode to
## localise the wiki.
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = "Privacy policy"; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
// moved below

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

# End of automatically generated settings.
# Add more configuration options below.

# Wiki configuration

$wgPasswordResetRoutes = false;
$wgEnableEmail = false;
$wgPasswordConfig['null'] = [ 'class' => InvalidPassword::class ];

## Time zone
$wgLocaltimezone = "UTC";

# Database settings

$wgDBtype = "mysql";
$wgDBserver = $_ENV['WIKI_DB_URI'];
$wgDBname = $_ENV['WIKI_DB_NAME'];
$wgDBuser = $_ENV['WIKI_DB_USER'];
$wgDBpassword = $_ENV['WIKI_DB_PASSWORD'];

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = true;

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = $_ENV['WIKI_UPGRADE_KEY'];

$wgSecretKey = $_ENV['WIKI_SECRET_KEY'];

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [ 'svg' => "$wgResourceBasePath/resources/assets/thumb/tg-star.svg" ];

## Favicon
$wgFavicon = "$wgResourceBasePath/resources/assets/thumb/tg-star.ico";

# Custom Namespaces

define("NS_TGMC", 4200); // This MUST be even.
define("NS_TGMC_TALK", 4201); // This MUST be the following odd integer.

// Add namespaces.
$wgExtraNamespaces[NS_TGMC] = "TGMC";
$wgExtraNamespaces[NS_TGMC_TALK] = "TGMC Talk";

# Group Permissions

$wgGroupPermissions['*']['read'] = true;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['autocreateaccount'] = true;
$wgGroupPermissions['*']['editmyprivateinfo'] = false;
$wgGroupPermissions['*']['viewmyprivateinfo'] = false;

$wgGroupPermissions['user']['edit'] = true;
$wgGroupPermissions['user']['move'] = false;
$wgGroupPermissions['user']['editmyusercss'] = false;
$wgGroupPermissions['user']['editmyuserjs'] = false;
$wgGroupPermissions['user']['editmyuserjsredirect'] = false;
$wgGroupPermissions['user']['editmyuserjson'] = false;
$wgGroupPermissions['user']['sendemail'] = false;

$wgGroupPermissions['WikiMaster'] = $wgGroupPermissions['suppress'];
$wgGroupPermissions['WikiMaster']['protect'] = true;
$wgGroupPermissions['WikiMaster']['editprotected'] = true;
$wgGroupPermissions['WikiMaster']['move'] = true;
$wgGroupPermissions['WikiMaster']['delete'] = true;
$wgGroupPermissions['WikiMaster']['undelete'] = true;
$wgGroupPermissions['WikiMaster']['deletedhistory'] = true;
$wgGroupPermissions['WikiMaster']['deletedtext'] = true;
$wgGroupPermissions['WikiMaster']['browsearchive'] = true;
$wgGroupPermissions['WikiMaster']['rollback'] = true;

$wgGroupPermissions['HeadAdministrator'] = $wgGroupPermissions['WikiMaster'];

$wgGroupPermissions['bureaucrat']['usermerge'] = true;
$wgGroupPermissions['bureaucrat']['disableaccount'] = true;

# Enabled extensions.

wfLoadExtension( 'Tabs' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'PluggableAuth' );
wfLoadExtension( 'WSOAuth' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'UserMerge' );
wfLoadExtension( 'DisableAccount' );

# WSOAuth configuration

$wgOAuthCustomAuthProviders = [
	'tgforum' => \WSOAuth\AuthenticationProvider\TgForumAuthProvider::class
];

$wgPluggableAuth_Config['tgforum'] = [
	'plugin' => 'WSOAuth',
	'data' => [
		'type' => 'tgforum',
		'clientId' => $_ENV['WIKI_OAUTH2_CLIENT_ID'],
		'clientSecret' => $_ENV['WIKI_OAUTH2_CLIENT_SECRET'],
	],
];
